"""Path constants and schema definitions."""
from pathlib import Path

# Project root: parent of this package
PROJECT_ROOT = Path(__file__).resolve().parent.parent
APP_DIR = PROJECT_ROOT

LOG_PATH = PROJECT_ROOT / "logs" / "fair_odds_logs.csv"

LOG_COLUMNS = [
    "timestamp", "game", "series_format", "market_type",
    "team_a", "team_b", "tier_a", "tier_b",
    "K", "decay", "floor",
    "raw_a", "raw_b", "adj_a", "adj_b", "adj_gap",
    "use_logistic", "a", "b", "use_clip", "clip_limit",
    "p_model", "odds_a", "odds_b", "fair_a", "fair_b", "ev_a_pct", "ev_b_pct",
    "p_decide", "ev_a_dec", "ev_b_dec", "decision", "decision_reason",
    "min_edge_pct", "prob_gap_pp", "shrink_target",
    "p_map_model", "p_map_decide", "draw_k",
    "p_a20", "p_draw", "p_b02",
    "odds_a20", "odds_draw", "odds_b02",
    "ev_a20_pct", "ev_draw_pct", "ev_b02_pct",
    "selected_outcome", "selected_prob", "selected_odds", "selected_ev_pct",
    "fair_a20_us", "fair_draw_us", "fair_b02_us",
]

INPLAY_LOG_PATH = PROJECT_ROOT / "logs" / "inplay_kappa_logs_clean.csv"
INPLAY_RESULTS_PATH = PROJECT_ROOT / "logs" / "inplay_match_results_clean.csv"
INPLAY_MAP_RESULTS_PATH = PROJECT_ROOT / "logs" / "inplay_map_results_clean.csv"

INPLAY_LOG_COLUMNS = [
    "timestamp", "game", "match_id",
    "contract_scope", "series_format", "maps_a_won", "maps_b_won",
    "team_a", "team_b", "map_name", "a_side_now",
    "rounds_a", "rounds_b", "map_index", "total_rounds", "prev_total_rounds", "gap_rounds", "gap_flag", "gap_reason",
    "buy_state_a", "buy_state_b", "econ_missing", "econ_fragile",
    "pistol_a", "pistol_b",
    "gap_delta", "streak_winner", "streak_len", "reversal", "n_tracked",
    "p0_map", "p_fair_map", "kappa_map",
    "p_fair", "band_level", "band_lo", "band_hi",
    "bid", "ask", "mid", "spread_abs", "spread_rel",
    "notes",
    "snapshot_idx", "half", "round_in_half", "is_ot", "round_in_map",
]

INPLAY_RESULTS_COLUMNS = ["match_id", "game", "team_a", "team_b", "winner", "timestamp"]
INPLAY_MAP_RESULTS_COLUMNS = ["match_id", "game", "map_index", "map_name", "team_a", "team_b", "winner", "timestamp"]

KAPPA_CALIB_PATH = PROJECT_ROOT / "config" / "kappa_calibration.json"
KAPPA_TRAIN_SCRIPT = PROJECT_ROOT / "ML" / "train_kappa_calibration.py"
P_CALIB_PATH = PROJECT_ROOT / "config" / "p_calibration.json"
P_CALIB_REPORT_PATH = PROJECT_ROOT / "config" / "p_calibration_report.json"
P_TRAIN_SCRIPT = PROJECT_ROOT / "ML" / "train_prob_calibration.py"

# CS2 persistent snapshot logging (replay + ML features)
CS2_REPLAY_SNAPSHOT_PARQUET_PATH = PROJECT_ROOT / "logs" / "cs2_replay_snapshots.parquet"
CS2_ML_FEATURE_PARQUET_PATH = PROJECT_ROOT / "logs" / "cs2_ml_features.parquet"

# Stable column order for replay parquet (broad, app-used/chart-used fields only; no UI state)
CS2_REPLAY_SNAPSHOT_COLUMNS = [
    "snapshot_ts_iso",
    "snapshot_ts_epoch_ms",
    "snapshot_schema_version",
    "app_build_version",
    "match_id",
    "t",
    "snapshot_ts",
    "series_fmt",
    "contract_scope",
    "maps_a_won",
    "maps_b_won",
    "rounds_a",
    "rounds_b",
    "map_index",
    "total_rounds",
    "prev_total_rounds",
    "gap_rounds",
    "gap_flag",
    "gap_reason",
    "econ_a",
    "econ_b",
    "econ_source_used",
    "team_a_money_total",
    "team_b_money_total",
    "econ_feed_a_raw",
    "econ_feed_b_raw",
    "econ_latched_a",
    "econ_latched_b",
    "econ_latched_round_number",
    "p0_series",
    "p0_map",
    "p_hat_map",
    "p_hat",
    "band_lo",
    "band_hi",
    "band_if_a_round",
    "band_if_b_round",
    "band_state_lo",
    "band_state_hi",
    "state_bound_lower",
    "state_bound_upper",
    "p_hat_current_helper_check",
    "state_band_contains_phat",
    "band_lo_map",
    "band_hi_map",
    "market_bid",
    "market_ask",
    "market_mid",
    "spread",
    "rel_spread",
    "dev_mid_pp",
    "buy_edge_pp",
    "sell_edge_pp",
    "feed_ts_epoch",
    "market_live_ts_epoch",
    "market_delayed_ts_epoch",
    "market_delay_sec_used",
    "market_delay_buffer_hit",
    "team_a_cash_total",
    "team_b_cash_total",
    "team_a_loadout_est_total",
    "team_b_loadout_est_total",
    "team_a_total_resources",
    "team_b_total_resources",
    "team_a_alive_cash_total",
    "team_b_alive_cash_total",
    "team_a_alive_loadout_est_total",
    "team_b_alive_loadout_est_total",
    "team_a_alive_total_resources",
    "team_b_alive_total_resources",
    "team_a_alive_count",
    "team_b_alive_count",
    "team_a_hp_alive_total",
    "team_b_hp_alive_total",
    "loadout_est_source",
    "p_base_frozen",
    "round_context_offset",
    "p_round_context",
    "round_ctx_econ_component",
    "round_ctx_loadout_component",
    "round_ctx_side_component",
    "round_ctx_armor_component",
    "p_mid_raw",
    "p_mid_clamped",
    "p_hat_final_source",
    "mid_adj_total",
    "mid_adj_alive",
    "mid_adj_bomb",
    "mid_adj_hp",
    "mid_time_scale",
    "mid_clamped_hit",
    "mid_clamp_distance",
    "mid_adj_armor",
    "mid_adj_loadout",
    "mid_reliability_mult",
    "mid_feature_has_armor",
    "mid_feature_has_alive_loadout",
    "mid_raw_total_pre_reliability",
    "mid_raw_total_post_reliability",
    "mid_alive_diff",
    "mid_hp_diff_alive",
    "mid_bomb_planted",
    "mid_time_remaining_s",
    "round_state_frozen_key",
    "round_state_frozen_lo",
    "round_state_frozen_hi",
    "round_state_band_if_a",
    "round_state_band_if_b",
    "rail_p_state_center",
    "rail_p_if_next_round_win",
    "rail_p_if_next_round_loss",
    "rail_upper_width",
    "rail_lower_width",
    "rail_asymmetry_ratio",
    "rail_current_rounds_a",
    "rail_current_rounds_b",
    "rail_model_version",
    "rail_anchor",
    "rail_if_a_wins",
    "rail_if_b_wins",
    "rail_base_rounds_a",
    "rail_base_rounds_b",
    "rail_cf_a_rounds_a",
    "rail_cf_a_rounds_b",
    "rail_cf_b_rounds_a",
    "rail_cf_b_rounds_b",
    "rail_endpoint_if_a_round",
    "rail_endpoint_if_b_round",
    "rail_endpoint_span_abs",
    "rail_endpoint_degenerate",
    "rail_endpoint_env_valid",
    "rail_endpoint_env_base_span_abs",
    "rail_endpoint_env_fraction_k",
    "rail_endpoint_env_round_leverage",
    "rail_endpoint_env_series_leverage",
    "rail_endpoint_env_half_width",
    "rail_endpoint_a_env_low",
    "rail_endpoint_a_env_high",
    "rail_endpoint_b_env_low",
    "rail_endpoint_b_env_high",
    "rail_endpoint_a_env_center",
    "rail_endpoint_b_env_center",
    "rail_terminal_override_a_used",
    "rail_terminal_override_b_used",
    "rail_terminal_if_a",
    "rail_terminal_if_b",
    "rail_terminal_smoothing_bypass_a",
    "rail_terminal_smoothing_bypass_b",
    "rail_band_if_a_round_pre_smooth",
    "rail_band_if_b_round_pre_smooth",
    "rail_band_if_a_round_post_smooth",
    "rail_band_if_b_round_post_smooth",
    "rail_terminal_endpoint_exact_preserved",
    "endpoint_pos_valid",
    "endpoint_pos_d_alive",
    "endpoint_pos_d_loadout",
    "endpoint_pos_d_armor",
    "endpoint_pos_score_a",
    "endpoint_pos_score_b",
    "endpoint_pos_a_quality_pos",
    "endpoint_pos_b_quality_pos",
    "endpoint_pos_a_active_dbg",
    "endpoint_pos_b_active_dbg",
    "endpoint_pos_a_active_within_env",
    "endpoint_pos_b_active_within_env",
    "endpoint_econ_valid",
    "endpoint_econ_d_alive_survival",
    "endpoint_econ_d_alive_loadout",
    "endpoint_econ_d_alive_cash",
    "endpoint_econ_score_a",
    "endpoint_econ_score_b",
    "endpoint_pos_third_driver_source",
    "drv_valid_microstate",
    "drv_valid_roundstate",
    "drv_team_a_side",
    "drv_bomb_planted",
    "drv_round_phase",
    "drv_round_time_remaining_s",
    "drv_alive_count_a",
    "drv_alive_count_b",
    "drv_hp_alive_total_a",
    "drv_hp_alive_total_b",
    "drv_alive_loadout_est_total_a",
    "drv_alive_loadout_est_total_b",
    "drv_alive_cash_total_a",
    "drv_alive_cash_total_b",
    "drv_source_contract",
    "phat_intra_valid",
    "phat_intra_side_known",
    "phat_intra_clock_known",
    "phat_intra_phase_mult",
    "phat_intra_urgency",
    "phat_intra_d_alive",
    "phat_intra_d_hp",
    "phat_intra_d_loadout",
    "phat_intra_bomb_term_signed",
    "phat_intra_clock_term_signed",
    "phat_intra_bomb_clock_combo_signed",
    "phat_intra_loadout_presence",
    "phat_intra_w_alive_eff",
    "phat_intra_score_alive",
    "phat_intra_score_hp",
    "phat_intra_score_loadout",
    "phat_intra_score_bomb",
    "phat_intra_score_clock",
    "phat_intra_score_bomb_clock_combo",
    "phat_intra_score_raw_pre_reliability",
    "phat_intra_score_raw_post_reliability",
    "phat_intra_q_intra_round_win_a_dbg",
    "rail_score_term",
    "rail_side_term",
    "rail_econ_term",
    "rail_loadout_term",
    "rail_round_end_latched",
    "rail_resolved_to_prev_endpoint",
    "rail_inputs_latched",
    "rail_used_smoothing",
    "rail_smoothing_alpha",
    "rail_input_econ_a",
    "rail_input_econ_b",
    "rail_input_loadout_a",
    "rail_input_loadout_b",
    "rail_series_maps_won_a",
    "rail_series_maps_won_b",
    "rail_series_term",
    "rail_series_asymmetry",
    "rail_anchor_canonical",
    "rail_if_a_canonical",
    "rail_if_b_canonical",
    "rail_if_a_adjusted",
    "rail_if_b_adjusted",
    "rail_asymmetry_bias",
    "rail_asymmetry_mult_a",
    "rail_asymmetry_mult_b",
    "rail_series_context_used",
    "rail_anchor_source",
    "round_transition_detected",
    "round_transition_prev_key",
    "round_transition_new_key",
    "round_transition_winner",
    "round_transition_resolved_p",
    "round_transition_resolution_source",
    "round_finalization_snap_occurred",
    "round_snap_applied_this_tick",
    "terminal_override_applied",
    "terminal_override_reason",
    "terminal_team_a_won",
    "p_hat_pre_terminal_override",
    "p_hat_post_terminal_override",
    "terminal_contract_scope",
    "terminal_series_target",
    "terminal_series_over",
    "terminal_map_over_detected",
    "terminal_override_blocked_reason",
    "p_hat_pre_bounds",
    "p_hat_post_round_bounds",
    "p_hat_post_map_bounds",
    "p_hat_bounds_mode",
    "p_hat_clipped_by_round",
    "p_hat_clipped_by_map",
    "p_hat_round_clip_delta",
    "p_hat_map_clip_delta",
    "p_hat_round_anchor_before_mid",
    "p_hat_round_soft_damped",
    "p_hat_round_soft_edge_factor",
    "p_hat_round_soft_room_frac",
    "p_hat_round_soft_delta_raw",
    "p_hat_round_soft_delta_applied",
    "p_hat_round_soft_direction",
    "p_hat_round_soft_hit",
    "p_series_if_a_wins_next_round",
    "p_series_if_b_wins_next_round",
    "q_intra_round_win_a",
    "q_intra_round_win_a_source",
    "q_intra_round_win_a_reason",
    "intra_score_raw",
    "intra_score_alive",
    "intra_score_hp",
    "intra_score_bomb",
    "intra_score_armor",
    "intra_score_loadout",
    "intra_score_post_reliability",
    "intra_score_time_scale",
    "p_hat_structural_mixture",
    "p_hat_between_endpoints",
    "endpoint_span_abs",
    "branch_endpoint_source_mode",
    "branch_endpoint_source_used",
    "branch_endpoint_source_reason",
    "branch_endpoint_selected_a",
    "branch_endpoint_selected_b",
    "branch_endpoint_selected_span_abs",
    "branch_endpoint_dynamic_available",
    "bo3_game_ended_flag",
    "bo3_match_ended_flag",
    "bo3_match_status_flag",
    "feed_terminal_used",
    "round_key_current",
    "round_key_frozen",
    "round_freeze_active",
    "round_freeze_key",
    "round_freeze_game_number",
    "round_freeze_rounds_a",
    "round_freeze_rounds_b",
    "round_freeze_phase_at_capture",
    "round_freeze_band_if_a",
    "round_freeze_band_if_b",
    "round_freeze_tick_ts",
    "round_snap_used",
    "round_snap_target_side",
    "round_snap_value",
    "round_snap_prev_freeze_key",
    "round_transition_tick_detected",
    "round_transition_used_prev_frozen_for_snap",
    "round_transition_latched_new_round_context",
    "round_transition_rail_computed_after_latch",
    "round_transition_game_number",
    "round_transition_prev_round_key",
    "round_transition_new_round_key",
    "latched_band_lo",
    "latched_p_base",
    "latched_round_key",
    "live_source_selected",
    "grid_valid",
    "grid_completeness_score",
    "grid_staleness_seconds",
    "grid_has_players",
    "grid_has_clock",
    "grid_used_reduced_features",
]

# Stable column order for ML feature parquet (curated + derived)
CS2_ML_FEATURE_COLUMNS = [
    "snapshot_ts_iso",
    "snapshot_ts_epoch_ms",
    "feature_schema_version",
    "match_id",
    "series_fmt",
    "contract_scope",
    "maps_a_won",
    "maps_b_won",
    "rounds_a",
    "rounds_b",
    "map_index",
    "total_rounds",
    "market_bid",
    "market_ask",
    "market_mid",
    "p_hat",
    "p_hat_map",
    "p0_map",
    "band_lo",
    "band_hi",
    "band_state_lo",
    "band_state_hi",
    "state_bound_lower",
    "state_bound_upper",
    "band_lo_map",
    "band_hi_map",
    "q_intra_round_win_a",
    "q_intra_round_win_a_source",
    "q_intra_round_win_a_reason",
    "branch_endpoint_source_mode",
    "branch_endpoint_source_used",
    "branch_endpoint_source_reason",
    "drv_valid_microstate",
    "drv_valid_roundstate",
    "drv_team_a_side",
    "drv_bomb_planted",
    "drv_round_phase",
    "drv_round_time_remaining_s",
    "drv_alive_count_a",
    "drv_alive_count_b",
    "drv_hp_alive_total_a",
    "drv_hp_alive_total_b",
    "drv_alive_loadout_est_total_a",
    "drv_alive_loadout_est_total_b",
    "drv_alive_cash_total_a",
    "drv_alive_cash_total_b",
    "team_a_money_total",
    "team_b_money_total",
    "team_a_loadout_est_total",
    "team_b_loadout_est_total",
    "econ_latched_a",
    "econ_latched_b",
    "round_transition_tick_detected",
    "round_transition_latched_new_round_context",
    "round_snap_applied_this_tick",
    "live_source_selected",
    "grid_valid",
    "grid_completeness_score",
    "round_band_width_pp",
    "map_band_width_pp",
    "kappa_band_width_pp",
    "dist_mid_to_round_lo_pp",
    "dist_mid_to_round_hi_pp",
    "dist_mid_to_map_lo_pp",
    "dist_mid_to_map_hi_pp",
    "dist_mid_to_kappa_lo_pp",
    "dist_mid_to_kappa_hi_pp",
    "p_hat_pos_in_round_band",
    "p_hat_pos_in_map_band",
    "q_minus_market_mid_pp",
    "p_hat_minus_p_hat_map_pp",
    "round_importance_proxy",
]
